---
- project:
    name: ui-tests
    description: "<h2>UI autotests</h2>"
    jobs:
    - ui-tests

- project:
    name: api-tests
    description: "<h2>API autotests</h2>"
    jobs:
    - api-tests

- project:
    name: runner-tests
    description: "<h2>Runner autotests</h2>"
    jobs:
    - runner-tests

- project:
    name: jobs-uploader
    description: "<h2>Jobs uploader</h2>"
    jobs:
    - jobs-uploader
